version: "3.9"


services:
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      # 👇 Ligne clé : génération automatique d’un cluster.id
      KAFKA_CLUSTER_ID: "b4U_ZKavQ9Shv1yaHjKQ2w"
    ports:
      - "9092:9092"

  scraper:
    build: ./scraper
    container_name: scraper
    depends_on:
      - kafka
    command: >
      sh -c "
      echo '⏳ Attente de Kafka...' &&
      sleep 10 &&
      python run_scraper.py
      "
