version: "3.9"

services:
  scraper:
    build: ./scraper
    container_name: scraper
    restart: "no"
    depends_on:
      - kafka  # le scraper attend que Kafka soit prêt

  kafka:
    image: confluentinc/cp-kafka:7.9.4
    container_name: kafka
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_BROKER_ID: 1
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
    ports:
      - "9092:9092"
      - "9093:9093"
